package cosas;


import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import juego.juego;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jesus Sainz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    static String nombre = "";
    static boolean nombrePreguntado = false;
    
    JLabel background;

    public Menu() {
        initComponents();

        setLocationRelativeTo(this);
        setResizable(false);

        setTitle("Juegos Espaciales");

        if (!nombrePreguntado) {
            nombre = JOptionPane.showInputDialog(this, "Introduce tu nombre");
        }

        BufferedImage imgFrancesco = null;
        BufferedImage imgMuchacho = null;
        BufferedImage imgSumas = null;
        BufferedImage imgPizarra = null;
        BufferedImage imgJuego = null;
        try {
            imgFrancesco = ImageIO.read(new File("francesco.jpg"));
            imgMuchacho = ImageIO.read(new File("elmuchacho.jpg"));
            imgSumas = ImageIO.read(new File("juegoFran.jpg"));
            imgJuego = ImageIO.read(new File("juego.png"));
            imgPizarra = ImageIO.read(new File("pizarra.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimgFrancesco = imgFrancesco.getScaledInstance(btnJuego1.getWidth(), btnJuego1.getHeight(),
                Image.SCALE_SMOOTH);
        Image dimgMuchacho = imgMuchacho.getScaledInstance(btnJuegoSamu.getWidth(), btnJuegoSamu.getHeight(),
                Image.SCALE_SMOOTH);
        Image dimgSumas = imgSumas.getScaledInstance(btnJuegoFran.getWidth(), btnJuegoFran.getHeight(),
                Image.SCALE_SMOOTH);
        Image dimgJuego = imgJuego.getScaledInstance(btnJuegoJavi.getWidth(), btnJuegoJavi.getHeight(),
                Image.SCALE_SMOOTH);
        Image dimgPizarra = imgPizarra.getScaledInstance(this.getWidth(), this.getHeight(),
                Image.SCALE_SMOOTH);
        btnJuego1.setIcon(new ImageIcon(dimgFrancesco));
        btnJuegoSamu.setIcon(new ImageIcon(dimgMuchacho));
        btnJuegoFran.setIcon(new ImageIcon(dimgSumas));
        btnJuegoJavi.setIcon(new ImageIcon(dimgJuego));
        
        setLayout(new BorderLayout());
        background = new JLabel(new ImageIcon(dimgPizarra));
        add(background);
        background.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJuego1 = new javax.swing.JButton();
        btnJuegoSamu = new javax.swing.JButton();
        btnJuegoJavi = new javax.swing.JButton();
        btnJuegoFran = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnJuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuego1ActionPerformed(evt);
            }
        });

        btnJuegoSamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoSamuActionPerformed(evt);
            }
        });

        btnJuegoJavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoJaviActionPerformed(evt);
            }
        });

        btnJuegoFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoFranActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Coches");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CalcuChapa");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CalcuTablas");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SumRest");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJuegoFran, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnJuegoJavi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnJuegoSamu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJuegoSamu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJuegoJavi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJuegoFran, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 * Boton para abrir el juego 1
 */
    private void btnJuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuego1ActionPerformed
        this.dispose();
        Frame frame = new Frame();
        frame.setVisible(true);
    }//GEN-LAST:event_btnJuego1ActionPerformed
/**
 * 
 * @param evt 
 * Boton para abrir el juego 2
 */
    private void btnJuegoSamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoSamuActionPerformed
        this.dispose();
        Juegoo frame = new Juegoo();
        frame.setVisible(true);
    }//GEN-LAST:event_btnJuegoSamuActionPerformed
/**
 * 
 * @param evt 
 * Boton para abrir el juego 3
 */
    private void btnJuegoFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoFranActionPerformed
        this.dispose();
        tablas frame = new tablas();
        frame.setVisible(true);
    }//GEN-LAST:event_btnJuegoFranActionPerformed
/**
 * 
 * @param evt 
 * Boton para abrir el juego 4
 */
    private void btnJuegoJaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoJaviActionPerformed
        this.dispose();
        juego frame = new juego();
        frame.setVisible(true);
    }//GEN-LAST:event_btnJuegoJaviActionPerformed

    public static String getNombre() {
        return nombre;
    }

    public static void setNombrePreguntado(boolean nombrePreguntado) {
        Menu.nombrePreguntado = nombrePreguntado;
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJuego1;
    private javax.swing.JButton btnJuegoFran;
    private javax.swing.JButton btnJuegoJavi;
    private javax.swing.JButton btnJuegoSamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
