
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author franc
 */
public class tablas extends javax.swing.JFrame {

    /**
     * Creates new form tablas
     */
    public tablas() {
        initComponents();
        this.setLocationRelativeTo(this);
        jPanel1.setVisible(true);
        paneldel1.setVisible(false);
        paneldel2.setVisible(false);
        paneldel3.setVisible(false);
        paneldel4.setVisible(false);
        paneldel5.setVisible(false);
        paneldel6.setVisible(false);
        paneldel7.setVisible(false);
        paneldel8.setVisible(false);
        paneldel9.setVisible(false);
        paneldel10.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneldel1 = new javax.swing.JPanel();
        comprobar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        paneldel2 = new javax.swing.JPanel();
        salir2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Comprobar2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        paneldel3 = new javax.swing.JPanel();
        salir3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comprobar3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        paneldel4 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        salir4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comprobar4 = new javax.swing.JButton();
        paneldel5 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        salir5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        comprobar5 = new javax.swing.JButton();
        paneldel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        salir6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comprobar6 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        paneldel7 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        salir7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        comprobar7 = new javax.swing.JButton();
        paneldel8 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        salir8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        comprobar8 = new javax.swing.JButton();
        paneldel9 = new javax.swing.JPanel();
        salir9 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        comprobar9 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        paneldel10 = new javax.swing.JPanel();
        salir10 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        comprobar10 = new javax.swing.JButton();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        paneldel1.setBackground(new java.awt.Color(0, 204, 102));

        comprobar1.setText("Comprobar");
        comprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 1.png"))); // NOI18N

        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("¿CUANTAS ESTÁN MAL?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        javax.swing.GroupLayout paneldel1Layout = new javax.swing.GroupLayout(paneldel1);
        paneldel1.setLayout(paneldel1Layout);
        paneldel1Layout.setHorizontalGroup(
            paneldel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir1))
            .addGroup(paneldel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(paneldel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comprobar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        paneldel1Layout.setVerticalGroup(
            paneldel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprobar1)
                .addGap(7, 7, 7)
                .addComponent(salir1))
        );

        getContentPane().add(paneldel1, "card2");

        paneldel2.setBackground(new java.awt.Color(204, 0, 204));

        salir2.setText("Salir");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setText("¿CUANTAS ESTÁN MAL?");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 2.png"))); // NOI18N

        Comprobar2.setText("Comprobar");
        Comprobar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comprobar2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        javax.swing.GroupLayout paneldel2Layout = new javax.swing.GroupLayout(paneldel2);
        paneldel2.setLayout(paneldel2Layout);
        paneldel2Layout.setHorizontalGroup(
            paneldel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel2Layout.createSequentialGroup()
                .addGroup(paneldel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Comprobar2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel2Layout.setVerticalGroup(
            paneldel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Comprobar2)
                .addGap(7, 7, 7)
                .addComponent(salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel2, "card3");

        paneldel3.setBackground(new java.awt.Color(204, 204, 0));

        salir3.setText("Salir");
        salir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setText("¿CUANTAS ESTÁN MAL?");

        comprobar3.setText("Comprobar");
        comprobar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar3ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 3.png"))); // NOI18N

        javax.swing.GroupLayout paneldel3Layout = new javax.swing.GroupLayout(paneldel3);
        paneldel3.setLayout(paneldel3Layout);
        paneldel3Layout.setHorizontalGroup(
            paneldel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel3Layout.createSequentialGroup()
                .addGroup(paneldel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel3Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar3))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel3Layout.setVerticalGroup(
            paneldel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar3)
                .addGap(7, 7, 7)
                .addComponent(salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel3, "card4");

        paneldel4.setBackground(new java.awt.Color(255, 0, 102));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 4.png"))); // NOI18N

        salir4.setText("Salir");
        salir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel10.setText("¿CUANTAS ESTÁN MAL?");

        comprobar4.setText("Comprobar");
        comprobar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldel4Layout = new javax.swing.GroupLayout(paneldel4);
        paneldel4.setLayout(paneldel4Layout);
        paneldel4Layout.setHorizontalGroup(
            paneldel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel4Layout.createSequentialGroup()
                .addGroup(paneldel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel4Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar4))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel4Layout.setVerticalGroup(
            paneldel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar4)
                .addGap(7, 7, 7)
                .addComponent(salir4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel4, "card5");

        paneldel5.setBackground(new java.awt.Color(0, 255, 204));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 5.png"))); // NOI18N

        salir5.setText("Salir");
        salir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel12.setText("¿CUANTAS ESTÁN MAL?");

        comprobar5.setText("Comprobar");
        comprobar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldel5Layout = new javax.swing.GroupLayout(paneldel5);
        paneldel5.setLayout(paneldel5Layout);
        paneldel5Layout.setHorizontalGroup(
            paneldel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel5Layout.createSequentialGroup()
                .addGroup(paneldel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel5Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar5))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel5Layout.setVerticalGroup(
            paneldel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel5Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel5Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar5)
                .addGap(7, 7, 7)
                .addComponent(salir5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel5, "card6");

        paneldel6.setBackground(new java.awt.Color(0, 204, 0));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 6.png"))); // NOI18N

        salir6.setText("Salir");
        salir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel14.setText("¿CUANTAS ESTÁN MAL?");

        comprobar6.setText("Comprobar");
        comprobar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar6ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        javax.swing.GroupLayout paneldel6Layout = new javax.swing.GroupLayout(paneldel6);
        paneldel6.setLayout(paneldel6Layout);
        paneldel6Layout.setHorizontalGroup(
            paneldel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel6Layout.createSequentialGroup()
                .addGroup(paneldel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel6Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar6))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel6Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel6Layout.setVerticalGroup(
            paneldel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel6Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel6Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar6)
                .addGap(7, 7, 7)
                .addComponent(salir6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel6, "card7");

        paneldel7.setBackground(new java.awt.Color(0, 255, 255));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 7.png"))); // NOI18N

        salir7.setText("Salir");
        salir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir7ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel16.setText("¿CUANTAS ESTÁN MAL?");

        comprobar7.setText("Comprobar");
        comprobar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldel7Layout = new javax.swing.GroupLayout(paneldel7);
        paneldel7.setLayout(paneldel7Layout);
        paneldel7Layout.setHorizontalGroup(
            paneldel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(paneldel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel7Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(comprobar7))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        paneldel7Layout.setVerticalGroup(
            paneldel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel7Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(paneldel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar7)
                .addGap(7, 7, 7)
                .addComponent(salir7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel7, "card8");

        paneldel8.setBackground(new java.awt.Color(255, 255, 0));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 8.png"))); // NOI18N

        salir8.setText("Salir");
        salir8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir8ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel18.setText("¿CUANTAS ESTÁN MAL?");

        comprobar8.setText("Comprobar");
        comprobar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldel8Layout = new javax.swing.GroupLayout(paneldel8);
        paneldel8.setLayout(paneldel8Layout);
        paneldel8Layout.setHorizontalGroup(
            paneldel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel8Layout.createSequentialGroup()
                .addGroup(paneldel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel8Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar8))
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel8Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        paneldel8Layout.setVerticalGroup(
            paneldel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel8Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel8Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar8)
                .addGap(7, 7, 7)
                .addComponent(salir8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel8, "card9");

        paneldel9.setBackground(new java.awt.Color(51, 255, 102));

        salir9.setText("Salir");
        salir9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir9ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel19.setText("¿CUANTAS ESTÁN MAL?");

        comprobar9.setText("Comprobar");
        comprobar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar9ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 9.png"))); // NOI18N

        javax.swing.GroupLayout paneldel9Layout = new javax.swing.GroupLayout(paneldel9);
        paneldel9.setLayout(paneldel9Layout);
        paneldel9Layout.setHorizontalGroup(
            paneldel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel9Layout.createSequentialGroup()
                .addGroup(paneldel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel9Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel9Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar9))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel9Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneldel9Layout.setVerticalGroup(
            paneldel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel9Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel9Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar9)
                .addGap(7, 7, 7)
                .addComponent(salir9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel9, "card10");

        paneldel10.setBackground(new java.awt.Color(255, 204, 51));

        salir10.setText("Salir");
        salir10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir10ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel21.setText("¿CUANTAS ESTÁN MAL?");

        comprobar10.setText("Comprobar");
        comprobar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar10ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabla del 10.png"))); // NOI18N

        javax.swing.GroupLayout paneldel10Layout = new javax.swing.GroupLayout(paneldel10);
        paneldel10.setLayout(paneldel10Layout);
        paneldel10Layout.setHorizontalGroup(
            paneldel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(paneldel10Layout.createSequentialGroup()
                .addGroup(paneldel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneldel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(paneldel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneldel10Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(comprobar10))
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel10Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneldel10Layout.setVerticalGroup(
            paneldel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldel10Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldel10Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobar10)
                .addGap(7, 7, 7)
                .addComponent(salir10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(paneldel10, "card11");

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jButton1.setText("INICIAR JUEGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suma caracoles.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton2))
        );

        getContentPane().add(jPanel1, "card12");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() == "2") {
            JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel2.setVisible(true);
            paneldel1.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel2.setVisible(false);
            paneldel1.setVisible(true);

        }
    }//GEN-LAST:event_comprobar1ActionPerformed

    private void Comprobar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comprobar2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedItem() == "3") {
                JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel3.setVisible(true);
            paneldel2.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel3.setVisible(false);
            paneldel2.setVisible(true);

        }
    }//GEN-LAST:event_Comprobar2ActionPerformed

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir2ActionPerformed

    private void salir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir3ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir3ActionPerformed

    private void comprobar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar3ActionPerformed
        // TODO add your handling code here:
        if (jComboBox3.getSelectedItem() == "4") {
             JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel4.setVisible(true);
            paneldel3.setVisible(false);
        } else {
             JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel4.setVisible(false);
            paneldel3.setVisible(true);

        }

    }//GEN-LAST:event_comprobar3ActionPerformed

    private void salir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir4ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir4ActionPerformed

    private void comprobar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar4ActionPerformed
        // TODO add your handling code here:
        if (jComboBox4.getSelectedItem() == "1") {
            JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel5.setVisible(true);
            paneldel4.setVisible(false);
        } else {
              JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel5.setVisible(false);
            paneldel4.setVisible(true);

        }
    }//GEN-LAST:event_comprobar4ActionPerformed

    private void salir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir5ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir5ActionPerformed

    private void comprobar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar5ActionPerformed
        // TODO add your handling code here:
        if (jComboBox5.getSelectedItem() == "2") {
            JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            
            paneldel6.setVisible(true);
            paneldel5.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel6.setVisible(false);
            paneldel5.setVisible(true);

        }
    }//GEN-LAST:event_comprobar5ActionPerformed

    private void salir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir6ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir6ActionPerformed

    private void comprobar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar6ActionPerformed
        // TODO add your handling code here:
        if (jComboBox6.getSelectedItem() == "5") {
            JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel7.setVisible(true);
            paneldel6.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel7.setVisible(false);
            paneldel6.setVisible(true);

        }
    }//GEN-LAST:event_comprobar6ActionPerformed

    private void salir7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir7ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir7ActionPerformed

    private void comprobar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar7ActionPerformed
        // TODO add your handling code here:
        if (jComboBox7.getSelectedItem() == "0") {
            JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel8.setVisible(true);
            paneldel7.setVisible(false);
        } else {
              JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel8.setVisible(false);
            paneldel7.setVisible(true);

        }
    }//GEN-LAST:event_comprobar7ActionPerformed

    private void salir8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir8ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir8ActionPerformed

    private void comprobar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar8ActionPerformed
        // TODO add your handling code here:
        if (jComboBox8.getSelectedItem() == "2") {
             JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel9.setVisible(true);
            paneldel8.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel9.setVisible(false);
            paneldel8.setVisible(true);

        }
    }//GEN-LAST:event_comprobar8ActionPerformed

    private void salir9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir9ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir9ActionPerformed

    private void comprobar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar9ActionPerformed
        // TODO add your handling code here:
        if (jComboBox9.getSelectedItem() == "10") {
             JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel10.setVisible(true);
            paneldel9.setVisible(false);
        } else {
             JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            paneldel10.setVisible(false);
            paneldel9.setVisible(true);

        }
    }//GEN-LAST:event_comprobar9ActionPerformed

    private void salir10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir10ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir10ActionPerformed

    private void comprobar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar10ActionPerformed
        // TODO add your handling code here:
        if (jComboBox4.getSelectedItem() == "1") {
             JOptionPane.showMessageDialog(null, "Has acertado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
               JOptionPane.showMessageDialog(null, "JUEGO COMPLETADO, ¡MUY BIEN!", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            jPanel1.setVisible(true);
            paneldel10.setVisible(false);
        } else {
              JOptionPane.showMessageDialog(null, "Has fallado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            jPanel1.setVisible(false);
            paneldel10.setVisible(true);

        }
    }//GEN-LAST:event_comprobar10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        paneldel1.setVisible(true);
        jPanel1.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        Menu.nombrePreguntado = true;
        this.dispose();
        Menu frame = new Menu();
        frame.setVisible(true);
    }//GEN-LAST:event_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprobar2;
    private javax.swing.JButton comprobar1;
    private javax.swing.JButton comprobar10;
    private javax.swing.JButton comprobar3;
    private javax.swing.JButton comprobar4;
    private javax.swing.JButton comprobar5;
    private javax.swing.JButton comprobar6;
    private javax.swing.JButton comprobar7;
    private javax.swing.JButton comprobar8;
    private javax.swing.JButton comprobar9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paneldel1;
    private javax.swing.JPanel paneldel10;
    private javax.swing.JPanel paneldel2;
    private javax.swing.JPanel paneldel3;
    private javax.swing.JPanel paneldel4;
    private javax.swing.JPanel paneldel5;
    private javax.swing.JPanel paneldel6;
    private javax.swing.JPanel paneldel7;
    private javax.swing.JPanel paneldel8;
    private javax.swing.JPanel paneldel9;
    private javax.swing.JButton salir1;
    private javax.swing.JButton salir10;
    private javax.swing.JButton salir2;
    private javax.swing.JButton salir3;
    private javax.swing.JButton salir4;
    private javax.swing.JButton salir5;
    private javax.swing.JButton salir6;
    private javax.swing.JButton salir7;
    private javax.swing.JButton salir8;
    private javax.swing.JButton salir9;
    // End of variables declaration//GEN-END:variables
}
